const LazyLoadExample = () => {
    return (
        <div>
            In its most general sense, the term "world" refers to the totality of entities, to the whole of reality or to everything that is.[1] The nature of the world has been conceptualized differently in different fields. Some conceptions see the world as unique while others talk of a "plurality of worlds". Some treat the world as one simple object while others analyze the world as a complex made up of many parts. In scientific cosmology the world or universe is commonly defined as "[t]he totality of all space and time; all that is, has been, and will be". Theories of modality, on the other hand, talk of possible worlds as complete and consistent ways how things could have been. Phenomenology, starting from the horizon of co-given objects present in the periphery of every experience, defines the world as the biggest horizon or the "horizon of all horizons". In philosophy of mind, the world is commonly contrasted with the mind as that which is represented by the mind. Theology conceptualizes the world in relation to God, for example, as God's creation, as identical to God or as the two being interdependent. In religions, there is often a tendency to downgrade the material or sensory world in favor of a spiritual world to be sought through religious practice. A comprehensive representation of the world and our place in it, as is commonly found in religions, is known as a worldview. Cosmogony is the field that studies the origin or creation of the world while eschatology refers to the science or doctrine of the last things or of the end of the world.

In various contexts, the term "world" takes a more restricted meaning associated, for example, with the Earth and all life on it, with humanity as a whole or with an international or intercontinental scope. In this sense, world history refers to the history of humanity as a whole or world politics is the discipline of political science studying issues that transcend nations and continents. Other examples include terms such as "world religion", "world language", "world government", "world war", "world population", "world economy" or "world championship".

Etymology
The English word world comes from the Old English weorold. The Old English is a reflex of the Common Germanic *weraldiz, a compound of weraz 'man' and aldiz 'age', thus literally meaning roughly 'age of man';[2] this word also led to Old Frisian warld, Old Saxon werold, Old Dutch werolt, Old High German weralt, and Old Norse verǫld.[3]

The corresponding word in Latin is mundus, literally 'clean, elegant', itself a loan translation of Greek cosmos 'orderly arrangement'. While the Germanic word thus reflects a mythological notion of a "domain of Man" (compare Midgard), presumably as opposed to the divine sphere on the one hand and the chthonic sphere of the underworld on the other, the Greco-Latin term expresses a notion of creation as an act of establishing order out of chaos.[4]

Conceptions
Different fields often work with quite different conceptions of the essential features associated with the term "world".[5][6] Some conceptions see the world as unique: there can be no more than one world. Others talk of a "plurality of worlds".[4] Some see worlds as complex things composed of many substances as their parts while others hold that worlds are simple in the sense that there is only one substance: the world as a whole.[7] Some characterize worlds in terms of objective spacetime while others define them relative to the horizon present in each experience. These different characterizations are not always exclusive: it may be possible to combine some without leading to a contradiction. Most of them agree that worlds are unified totalities.[5][6]

Monism and pluralism
Monism is a thesis about oneness: that only one thing exists in a certain sense. The denial of monism is pluralism, the thesis that, in a certain sense, more than one thing exists.[7] There are many forms of monism and pluralism, but in relation to the world as a whole, two are of special interest: existence monism/pluralism and priority monism/pluralism. Existence monism states that the world is the only concrete object there is.[7][8][9] This means that all the concrete "objects" we encounter in our daily lives, including apples, cars and ourselves, are not truly objects in a strict sense. Instead, they are just dependent aspects of the world-object.[7] Such a world-object is simple in the sense that it does not have any genuine parts. For this reason, it has also been referred to as "blobject" since it lacks an internal structure just like a blob.[10] Priority monism allows that there are other concrete objects besides the world.[7] But it holds that these objects do not have the most fundamental form of existence, that they somehow depend on the existence of the world.[9][11] The corresponding forms of pluralism, on the other hand, state that the world is complex in the sense that it is made up of concrete, independent objects.[7]

Scientific cosmology
Scientific cosmology can be defined as the science of the universe as a whole. In it, the terms "universe" and "cosmos" are usually used as synonyms for the term "world".[12] One common definition of the world/universe found in this field is as "[t]he totality of all space and time; all that is, has been, and will be".[13][5][6] Some definitions emphasize that there are two other aspects to the universe besides spacetime: forms of energy or matter, like stars and particles, and laws of nature.[14] Different world-conceptions in this field differ both concerning their notion of spacetime and of the contents of spacetime. The theory of relativity plays a central role in modern cosmology and its conception of space and time. An important difference from its predecessors is that it conceives space and time not as distinct dimensions but as a single four-dimensional manifold called spacetime.[15] This can be seen in special relativity in relation to the Minkowski metric, which includes both spatial and temporal components in its definition of distance.[16] General relativity goes one step further by integrating the concept of mass into the concept of spacetime as its curvature.[16] Quantum cosmology, on the other hand, uses a classical notion of spacetime and conceives the whole world as one big wave function expressing the probability of finding particles in a given location.[17]

Theories of modality
The world-concept plays an important role in many modern theories of modality, usually in the form of possible worlds.[18] A possible world is a complete and consistent way how things could have been.[19] The actual world is a possible world since the way things are is a way things could have been. But there are many other ways things could have been besides how they actually are. For example, Hillary Clinton did not win the 2016 US election, but she could have won them. So there is a possible world in which she did. There is a vast number of possible worlds, one corresponding to each such difference, no matter how small or big, as long as no outright contradictions are introduced this way.[19]

Possible worlds are often conceived as abstract objects, for example, in terms of non-obtaining states of affairs or as maximally consistent sets of propositions.[20][21] On such a view, they can even be seen as belonging to the actual world.[22] Another way to conceive possible worlds, made famous by David Lewis, is as concrete entities.[4] On this conception, there is no important difference between the actual world and possible worlds: both are conceived as concrete, inclusive and spatiotemporally connected.[19] The only difference is that the actual world is the world we live in, while other possible worlds are not inhabited by us but by our counterparts.[23] Everything within a world is spatiotemporally connected to everything else but the different worlds do not share a common spacetime: They are spatiotemporally isolated from each other.[19] This is what makes them separate worlds.[23]

It has been suggested that, besides possible worlds, there are also impossible worlds. Possible worlds are ways things could have been, so impossible worlds are ways things could not have been.[24][25] Such worlds involve a contradiction, like a world in which Hillary Clinton both won and lost the 2016 US election. Both possible and impossible worlds have in common the idea that they are totalities of their constituents.[24][26]

Phenomenology
Within phenomenology, worlds are defined in terms of horizons of experiences.[5][6] When we perceive an object, like a house, we do not just experience this object at the center of our attention but also various other objects surrounding it, given in the periphery.[27] The term "horizon" refers to these co-given objects, which are usually experienced only in a vague, indeterminate manner.[28][29] The perception of a house involves various horizons, corresponding to the neighborhood, the city, the country, the Earth, etc. In this context, the world is the biggest horizon or the "horizon of all horizons".[27][5][6] It is common among phenomenologists to understand the world not just as a spatiotemporal collection of objects but as additionally incorporating various other relations between these objects. These relations include, for example, indication-relations that help us anticipate one object given the appearances of another object and means-end-relations or functional involvements relevant for practical concerns.[27]

Philosophy of mind
In philosophy of mind, the term "world" is commonly used in contrast to the term "mind" as that which is represented by the mind. This is sometimes expressed by stating that there is a gap between mind and world and that this gap needs to be overcome for representation to be successful.[30][31][32] One of the central problems in philosophy of mind is to explain how the mind is able to bridge this gap and to enter into genuine mind-world-relations, for example, in the form of perception, knowledge or action.[33][34] This is necessary for the world to be able to rationally constrain the activity of the mind.[30][35] According to a realist position, the world is something distinct and independent from the mind.[36] Idealists, on the other hand, conceive of the world as partially or fully determined by the mind.[36][37] Immanuel Kant's transcendental idealism, for example, posits that the spatiotemporal structure of the world is imposed by the mind on reality but lacks independent existence otherwise.[38] A more radical idealist conception of the world can be found in Berkeley's subjective idealism, which holds that the world as a whole, including all everyday objects like tables, cats, trees and ourselves, "consists of nothing but minds and ideas".[39]

Theology
Different theological positions hold different conceptions of the world based on its relation to God. Classical theism states that God is wholly distinct from the world. But the world depends for its existence on God, both because God created the world and because He maintains or conserves it.[40][41][42] This is sometimes understood in analogy to how humans create and conserve ideas in their imagination, with the difference being that the divine mind is vastly more powerful.[40] On such a view, God has absolute, ultimate reality in contrast to the lower ontological status ascribed to the world.[42] God's involvement in the world is often understood along the lines of a personal, benevolent God who looks after and guides His creation.[41] Deists agree with theists that God created the world but deny any subsequent, personal involvement in it.[43] Pantheists, on the other hand, reject the separation between God and world. Instead, they claim that the two are identical. This means that there is nothing to the world that does not belong to God and that there is nothing to God beyond what is found in the world.[42][44] Panentheism constitutes a middle ground between theism and pantheism. Against theism, It holds that God and the world are interrelated and depend on each other. Against pantheism, it holds that there is no outright identity between the two.[42][45] Atheists, on the other hand, deny the existence of God and thereby of conceptions of the world based on its relation to God.

History of philosophy
In philosophy, the term world has several possible meanings. In some contexts, it refers to everything that makes up reality or the physical universe. In others, it can mean have a specific ontological sense (see world disclosure). While clarifying the concept of world has arguably always been among the basic tasks of Western philosophy, this theme appears to have been raised explicitly only at the start of the twentieth century[46] and has been the subject of continuous debate. The question of what the world is has by no means been settled.

Parmenides
The traditional interpretation of Parmenides' work is that he argued that the everyday perception of reality of the physical world (as described in doxa) is mistaken, and that the reality of the world is 'One Being' (as described in aletheia): an unchanging, ungenerated, indestructible whole.

Plato
Plato is well known for his theory of forms, which posits the existence of two different worlds: the sensible world and the intelligible world. The sensible world is the world we live in, filled with changing physical things we can see, touch and interact with. The intelligible world, on the other hand, is the world of invisible, eternal, changeless forms like goodness, beauty, unity and sameness.[47][48][49] Plato ascribes a lower ontological status to the sensible world, which only imitates the world of forms. This is due to the fact that physical things exist only to the extent that they participate in the forms that characterize them, while the forms themselves have an independent manner of existence.[47][48][49] In this sense, the sensible world is a mere replication of the perfect exemplars found in the world of forms: it never lives up to the original. In the allegory of the cave, Plato compares the physical things we are familiar with to mere shadows of the real things. But not knowing the difference, the prisoners in the cave mistake the shadows for the real things.[50]

Hegel
In Georg Wilhelm Friedrich Hegel's philosophy of history, the expression Weltgeschichte ist Weltgericht (World History is a tribunal that judges the World) is used to assert the view that History is what judges men, their actions and their opinions. Science is born from the desire to transform the World in relation to Man; its final end is technical application.

Schopenhauer
The World as Will and Representation is the central work of Arthur Schopenhauer. Schopenhauer saw the human will as our one window to the world behind the representation; the Kantian thing-in-itself. He believed, therefore, that we could gain knowledge about the thing-in-itself, something Kant said was impossible, since the rest of the relationship between representation and thing-in-itself could be understood by analogy to the relationship between human will and human body.

Wittgenstein
Two definitions that were both put forward in the 1920s, however, suggest the range of available opinion. "The world is everything that is the case", wrote Ludwig Wittgenstein in his influential Tractatus Logico-Philosophicus, first published in 1921.[51] This definition would serve as the basis of logical positivism, with its assumption that there is exactly one world, consisting of the totality of facts, regardless of the interpretations that individual people may make of them.

Heidegger
Martin Heidegger, meanwhile, argued that "the surrounding world is different for each of us, and notwithstanding that we move about in a common world".[52] The world, for Heidegger, was that into which we are always already "thrown" and with which we, as beings-in-the-world, must come to terms. His conception of "world disclosure" was most notably elaborated in his 1927 work Being and Time.

Eugen Fink
"World" is one of the key terms in Eugen Fink's philosophy.[53] He thinks that there is a misguided tendency in western philosophy to understand the world as one enormously big thing containing all the small everyday things we are familiar with.[54] He sees this view as a form of forgetfulness of the world and tries to oppose it by what he calls the "cosmological difference": the difference between the world and the inner-worldly things it contains.[54] On his view, the world is the totality of the inner-worldly things that transcends them.[55] It is itself groundless but it provides a ground for things. It therefore cannot be identified with a mere container. Instead, the world gives appearance to inner-worldly things, it provides them with a place, a beginning and an end.[54] One difficulty in investigating the world is that we never encounter it since it is not just one more thing that appears to us. This is why Fink uses the notion of play or playing to elucidate the nature of the world.[54][55] He sees play as a symbol of the world that is both part of it and that represents it.[56] Play usually comes with a form of imaginary play-world involving various things relevant to the play. But just like the play is more than the imaginary realities appearing in it so the world is more than the actual things appearing in it.[54][56]

Goodman
The concept of worlds plays a central role in Nelson Goodman's late philosophy.[57] He argues that we need to posit different worlds in order to account for the fact that there are different incompatible truths found in reality.[58] Two truths are incompatible if they ascribe incompatible properties to the same thing.[57] This happens, for example, when we assert both that the earth moves and that the earth is at rest. These incompatible truths correspond to two different ways of describing the world: heliocentrism and geocentrism.[58] Goodman terms such descriptions "world versions". He holds a correspondence theory of truth: a world version is true if it corresponds to a world. Incompatible true world versions correspond to different worlds.[58] It is common for theories of modality to posit the existence of a plurality of possible worlds. But Goodman's theory is different since it posits a plurality not of possible but of actual worlds.[57][5] Such a position is in danger of involving a contradiction: there cannot be a plurality of actual worlds if worlds are defined as maximally inclusive wholes.[57][5] This danger may be avoided by interpreting Goodman's world-concept not as maximally inclusive wholes in the absolute sense but in relation to its corresponding world-version: a world contains all and only the entities that its world-version describes.[57][5]


        </div>
    )
}

export default LazyLoadExample